apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "demo-app.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "demo-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  type: ClusterIP
